#!/bin/bash
# Show available Go1 environments and project info

echo "======================================"
echo "Go1 Walking Policy Project"
echo "======================================"
echo ""
echo "📁 Project Location:"
echo "   /home/maxime/my_go1_project/"
echo ""
echo "📝 Project Structure:"
echo "   my_go1_project/"
echo "   ├── README.md                    # Documentation"
echo "   ├── train.sh                     # Quick training script"
echo "   ├── config/"
echo "   │   ├── go1_walking_env_cfg.py  # Environment config (copy)"
echo "   │   └── go1_ppo_cfg.py          # PPO config (copy)"
echo "   └── scripts/"
echo "       ├── train_go1_walking.py    # Training script"
echo "       ├── play_go1_walking.py     # Testing script"
echo "       └── verify_setup.py         # Setup verification"
echo ""
echo "🤖 Available Go1 Environments:"
echo ""
echo "  Training Environments:"
echo "    • Isaac-Velocity-Rough-Unitree-Go1-v0"
echo "      → Train on rough terrain (stairs, slopes, obstacles)"
echo "      → 4096 parallel environments"
echo "      → Full curriculum learning"
echo ""
echo "    • Isaac-Velocity-Flat-Unitree-Go1-v0"
echo "      → Train on flat terrain"
echo "      → Easier task, faster convergence"
echo ""
echo "  Play/Test Environments:"
echo "    • Isaac-Velocity-Rough-Unitree-Go1-Play-v0"
echo "      → Test trained policy on rough terrain"
echo "      → 50 environments (less GPU memory)"
echo ""
echo "    • Isaac-Velocity-Flat-Unitree-Go1-Play-v0"
echo "      → Test trained policy on flat terrain"
echo ""
echo "🚀 Quick Start Commands:"
echo ""
echo "  1. Train with default settings (recommended):"
echo "     cd /home/maxime/my_go1_project"
echo "     ./train.sh"
echo ""
echo "  2. Train with GUI (slower but visual):"
echo "     ./train.sh --gui"
echo ""
echo "  3. Train on flat terrain:"
echo "     ./train.sh --task Isaac-Velocity-Flat-Unitree-Go1-v0"
echo ""
echo "  4. Train with custom parameters:"
echo "     ./train.sh --num_envs 2048 --max_iterations 3000"
echo ""
echo "  5. Test trained policy:"
echo "     cd /home/maxime/IsaacLab-main"
echo "     bash isaaclab.sh -p /home/maxime/my_go1_project/scripts/play_go1_walking.py \\"
echo "         --checkpoint logs/rsl_rl/unitree_go1_rough/<timestamp>/model_*.pt"
echo ""
echo "📊 Monitor Training:"
echo "   tensorboard --logdir logs/rsl_rl/"
echo ""
echo "💾 Training logs saved to:"
echo "   logs/rsl_rl/unitree_go1_rough/<timestamp>/"
echo ""
echo "🎯 Key Configuration Files to Modify:"
echo ""
echo "  Environment (my_go1_project/config/go1_walking_env_cfg.py):"
echo "    • Observation space"
echo "    • Action scaling"
echo "    • Reward weights"
echo "    • Terrain difficulty"
echo "    • Termination conditions"
echo ""
echo "  Training (my_go1_project/config/go1_ppo_cfg.py):"
echo "    • Learning rate"
echo "    • Batch size"
echo "    • Number of epochs"
echo "    • Network architecture"
echo ""
echo "📖 For detailed documentation, see:"
echo "   /home/maxime/my_go1_project/README.md"
echo ""
echo "======================================"
